### ISSUE TITLE
Шаблон подразумевает, что все поля всегда заполнены

### ISSUE THREAD

**Issue by dandaka** [accuratencom/form-sender#2]
**Сейчас**

Шаблон подразумевает, что поля всегда заполнены:

Имя: {{name}}
Телефон: {{tel}}
Email: {{_replyto}}
Задача: {{message}}

**Нужно**

Можно часть полей не заполнять, и заголовки эти не будут появляться в сообщениях.

**Comment by mx-studio** [comment]
Реализовано. Для того, чтобы оставить и текущую логику работы (когда строка полностью не удаляется) и при этом добавить новую функциональность, данная функциональность реализована путем добавления к полю суффикса :removeLineIfNotExist. Пример шаблона:

_К нам обратился клиент с просьбой связаться. Вот его данные:

Имя: {{name:removeLineIfNotExist}}
Телефон: {{tel:removeLineIfNotExist}}
Email: {{_replyto:removeLineIfNotExist}}
Задача: {{message:removeLineIfNotExist}}

Давайте с ним свяжемся и продадим наши услуги! @dandaka, вперед!_

**Comment by dandaka** [comment]
Вот такое прилетело:

К нам обратился клиент с просьбой связаться. Вот его данные:

Имя: Vladislav Rafeev
Телефон: +79118554541
Email: {{_replyto:removeLineIfNotExist}}
Задача: {{message:removeLineIfNotExist}}

Давайте с ним свяжемся и продадим наши услуги! @dandaka, вперед!

**Comment by mx-studio** [comment]
Изменив шаблон, точно не забыли новый файл form-sender.php заменить на том сайте, где проверяете?

**Comment by mx-studio** [comment]
Выглядит, будто этот файл у вас остался старым

**Comment by dandaka** [comment]
Нет, файл актуальный. Он обновляется из репозитория автоматически. Вместе с файлом шаблонов.

http://take.ms/qAxDy

Тестирую на accuraten.com

**Comment by mx-studio** [comment]
Проверяю на своей версии - без заполненного email, при шаблоне, приведенном на скриншоте, получаю в slack сообщение, приведенное на скриншоте https://db.tt/HdAd3cIiYk
Скиньте файл вашего шаблона (не просто текст, а именно сам файл), на котором вы сейчас проверяете, попробую его себе подставить. Если проблема все равно не проявится, тогда нужен будет доступ к сайту, на котором проверяете или его бэкап.

**Comment by dandaka** [comment]
http://files.accuraten.com/form-sender/slack.html

**Comment by dandaka** [comment]
Или вам его скачать и приложить сюда?

**Comment by mx-studio** [comment]
Лучше сюда приложите

**Comment by dandaka** [comment]
Сюда никак, выслал почтой

**Comment by mx-studio** [comment]
Проверил, как и полагал, дело оказалось в символе переноса строки - разные редакторы бывает разные символы переноса строки используют. Сейчас выгрузил измененный form-sender.php, он у меня теперь работает и с вашим шаблоном, и с моим
